# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "/Users/bs/Desktop/Calvision/Simulation/Geant4/geant4-v11.3.0;/Users/bs/Desktop/Calvision/Simulation/Geant4/geant4-v11.3.0-build")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "Development;Examples;Runtime;Unspecified")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "cmake, make, g++")
set(CPACK_DEBIAN_PACKAGE_GENERATE_SHLIBS "TRUE")
set(CPACK_DEBIAN_PACKAGE_GENERATE_SHLIBS_POLICY "=")
set(CPACK_DEBIAN_PACKAGE_RECOMMENDS "libexpat1-dev, libxerces-c-dev, zlib1g-dev")
set(CPACK_DEBIAN_PACKAGE_SECTION "science")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS "TRUE")
set(CPACK_DEBIAN_PACKAGE_SUGGESTS "")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/Applications/CMake.app/Contents/share/cmake-3.31/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "Geant4 built using CMake")
set(CPACK_GENERATOR "TGZ;TXZ;ZIP")
set(CPACK_IGNORE_FILES "/Users/bs/Desktop/Calvision/Simulation/Geant4/geant4-v11.3.0-build/;.clang-format;.clang-tidy;README.*;CONTRIBUTING.*;CODING_GUIDELINES.*;RELEASE_MANAGEMENT.rst;SHIFTERS.rst;/GitUtilities/;/tests/;/ReleaseNotes/development;/benchmarks/;/verification/;/test.*/;/doc.*/;/benchmark.*/;~$;/CVS/;/.svn/;/\\\\.svn/;/.git/;.gitignore;/.github/;/.gitlab;/\\\\.git/;\\\\.swp$;\\\\.swp$;\\.swp;\\\\.#;/#")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALLED_DIRECTORIES "/Users/bs/Desktop/Calvision/Simulation/Geant4/geant4-v11.3.0;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_INSTALL_SCRIPTS "/Users/bs/Desktop/Calvision/Simulation/Geant4/geant4-v11.3.0-build/source_package_extras.cmake")
set(CPACK_MODULE_PATH "/Users/bs/Desktop/Calvision/Simulation/Geant4/geant4-v11.3.0/cmake/Modules")
set(CPACK_NSIS_DISPLAY_NAME "Geant4-11.3")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "Geant4-11.3")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJDUMP_EXECUTABLE "/Library/Developer/CommandLineTools/usr/bin/objdump")
set(CPACK_OSX_SYSROOT "/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk")
set(CPACK_OUTPUT_CONFIG_FILE "/Users/bs/Desktop/Calvision/Simulation/Geant4/geant4-v11.3.0-build/CPackConfig.cmake")
set(CPACK_PACKAGE_CHECKSUM "SHA256")
set(CPACK_PACKAGE_CONTACT "Geant4 Collaboration <https://geant4.cern.ch/collaboration/contacts>")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/Users/bs/Desktop/Calvision/Simulation/Geant4/geant4-v11.3.0-build/README.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "C++ toolkit for simulating the passage of particles through matter")
set(CPACK_PACKAGE_FILE_NAME "geant4-v11.3.0")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://geant4.cern.ch")
set(CPACK_PACKAGE_ICON "/Users/bs/Desktop/Calvision/Simulation/Geant4/geant4-v11.3.0/cmake/Templates/g4_small.bmp")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "Geant4-11.3")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "Geant4-11.3")
set(CPACK_PACKAGE_NAME "geant4")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Geant4 Collaboration")
set(CPACK_PACKAGE_VERSION "11.3.0")
set(CPACK_PACKAGE_VERSION_MAJOR "11")
set(CPACK_PACKAGE_VERSION_MINOR "3")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_PROJECT_CONFIG_FILE "/Users/bs/Desktop/Calvision/Simulation/Geant4/geant4-v11.3.0-build/CMakeCPackOptions.cmake")
set(CPACK_RESOURCE_FILE_LICENSE "/Users/bs/Desktop/Calvision/Simulation/Geant4/geant4-v11.3.0-build/LICENSE.txt")
set(CPACK_RESOURCE_FILE_README "/Users/bs/Desktop/Calvision/Simulation/Geant4/geant4-v11.3.0-build/README.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/Applications/CMake.app/Contents/share/cmake-3.31/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TGZ;TXZ;ZIP")
set(CPACK_SOURCE_IGNORE_FILES "/Users/bs/Desktop/Calvision/Simulation/Geant4/geant4-v11.3.0-build/;.clang-format;.clang-tidy;README.*;CONTRIBUTING.*;CODING_GUIDELINES.*;RELEASE_MANAGEMENT.rst;SHIFTERS.rst;/GitUtilities/;/tests/;/ReleaseNotes/development;/benchmarks/;/verification/;/test.*/;/doc.*/;/benchmark.*/;~$;/CVS/;/.svn/;/\\\\.svn/;/.git/;.gitignore;/.github/;/.gitlab;/\\\\.git/;\\\\.swp$;\\\\.swp$;\\.swp;\\\\.#;/#")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/Users/bs/Desktop/Calvision/Simulation/Geant4/geant4-v11.3.0;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/Users/bs/Desktop/Calvision/Simulation/Geant4/geant4-v11.3.0-build/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "geant4-v11.3.0")
set(CPACK_SOURCE_STRIP_FILES "")
set(CPACK_SOURCE_TOPLEVEL_TAG "Darwin-Source")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Darwin")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Darwin-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/Users/bs/Desktop/Calvision/Simulation/Geant4/geant4-v11.3.0-build/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
