# This file is generated by the Geant4 CMake buildsystem and should not be editted
#
# This file stores paths and settings to external libraries found and used by this
# install of Geant4 when it was built.

macro(geant4_set_and_check_package_variable _name _value _type _docstring)
  if(DEFINED ${_name})
    if(NOT ("${${_name}}" STREQUAL "${_value}"))
      message(WARNING "Value of '${_name}' is already set and does not match value set at Geant4 build-time")
    endif()
  else()
    set(${_name} ${_value} CACHE ${_type} "${_docstring}")
  endif()
endmacro()


# EXPAT Build Time Settings
geant4_set_and_check_package_variable(EXPAT_INCLUDE_DIR "/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include" PATH "Path to a file.")
geant4_set_and_check_package_variable(EXPAT_LIBRARY "/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/lib/libexpat.tbd" PATH "no documentation, not a cache value")
geant4_set_and_check_package_variable(EXPAT_LIBRARY_RELEASE "/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/lib/libexpat.tbd" FILEPATH "Path to a library.")

# TBB Build Time Settings
